#paraview_config.yaml
paraview_path: "C:\\Program Files\\ParaView 5.9.1-Windows-Python3.8-msvc2017-64bit\\bin\\paraview.exe"
paraview_pvpython_path: "\\Program Files\\ParaView 5.9.1-Windows-Python3.8-msvc2017-64bit\\bin\\pvpython.exe"